# -*- coding: utf-8 -*-
"""HousingDAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecmIcUtJ2tnRyhA6Puizul8v1_0rODUD
"""

pd.set_option('display.float_format', '{:.2f}'.format)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import kmeans_plusplus
import xgboost as xgb
import seaborn as sns
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable

# Read in CSV data
df = pd.read_csv("zillowDataFinal.csv")
# Drop rows with a price of zero
df = df[df['price'] != 0]
# Drop rows with missing values
df = df.dropna()
# Print head sorted by price
df.head()

df['log_price'] = np.log1p(df['price'])
display(df[['price', 'log_price']].head())

"""Filter for outliers

"""

# Calculate Q1, Q3, and IQR for log_price
Q1 = df['log_price'].quantile(0.25)
Q3 = df['log_price'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
# lower_bound = Q1
# upper_bound = Q3
# Filter out the outliers
df_filtered = df[(df['log_price'] >= lower_bound) & (df['log_price'] <= upper_bound)].copy()

print(f"Original number of rows: {len(df)}")
print(f"Number of rows after outlier filtering: {len(df_filtered)}")

from scipy.stats import norm, lognorm # Import for normal and log-normal distributions

# Calculate parameters for a log-normal distribution based on the filtered log_price
mean_log_price = df_filtered['log_price'].mean()
stddev_log_price = df_filtered['log_price'].std()

fig, axes = plt.subplots(3, 1, figsize=(10, 15)) # Changed to 3x1 grid

# Parameter to control bin size for all histograms in this cell
bins_param = 50 # You can change this value (e.g., 'auto', 30, 100)

# Get colors from the viridis palette
viridis_colors = sns.color_palette('viridis', n_colors=20)

# --- Plot 1: Distribution of Original Price (Unfiltered) ---
sns.histplot(df['price'], stat='density', ax=axes[0], kde=False, color=viridis_colors[1], alpha=0.7)
axes[0].set_title('Distribution of Original Price (Unfiltered)')
axes[0].set_xlabel('Price')
axes[0].set_ylabel('Density')

# Removed Plot 2: Distribution of Log-Transformed Price (Unfiltered)

# --- Plot 2 (formerly Plot 3): Distribution of Original Price (Filtered) with Log-Normal Fit ---
# Create a range for the original price axis, ensuring it covers the data range of the *filtered* data
x_price_filtered = np.linspace(np.expm1(df_filtered['log_price'].min()), np.expm1(df_filtered['log_price'].max()), 500)
# Calculate the Log-Normal PDF for these values using parameters from filtered log_price
pdf_lognorm_fit = lognorm.pdf(x_price_filtered, s=stddev_log_price, scale=np.exp(mean_log_price))

sns.histplot(np.expm1(df_filtered['log_price']), stat='density', ax=axes[1], kde=False, color=viridis_colors[12], alpha=0.7, bins=bins_param)
axes[1].plot(x_price_filtered, pdf_lognorm_fit, color='blue', linestyle='--', label='Log-Normal Fit')
axes[1].set_title('Distribution of Original Price (Filtered) with Log-Normal Fit')
axes[1].set_xlabel('Price')
axes[1].set_ylabel('Density')
axes[1].legend()
# Explicitly set x-axis limits to fit the data using df_filtered['price']
axes[1].set_xlim(df_filtered['price'].min(), df_filtered['price'].max())

# --- Plot 3 (formerly Plot 4): Distribution of Log-Transformed Price (Filtered) with Normal Fit ---
# Create a range for the log_price axis, ensuring it covers the data range of the filtered data
x_log_price_filtered = np.linspace(df_filtered['log_price'].min(), df_filtered['log_price'].max(), 500)
# Calculate the Normal PDF for these values using parameters from filtered log_price
pdf_normal_fit = norm.pdf(x_log_price_filtered, loc=mean_log_price, scale=stddev_log_price)

sns.histplot(df_filtered['log_price'], stat='density', ax=axes[2], kde=False, color=viridis_colors[18], alpha=0.7, bins=bins_param)
axes[2].plot(x_log_price_filtered, pdf_normal_fit, color='blue', linestyle='--', label='Normal Fit')
axes[2].set_title('Distribution of Log-Transformed Price (Filtered) with Normal Fit')
axes[2].set_xlabel('Log(Price)')
axes[2].set_ylabel('Density')
axes[2].legend()
# Explicitly set x-axis limits to fit the data
axes[2].set_xlim(df_filtered['log_price'].min(), df_filtered['log_price'].max())

plt.tight_layout()
plt.show()

from pyproj import CRS, Transformer

# Define the source CRS (WGS84 geographic coordinates)
source_crs = CRS("EPSG:4326")
# Define the target CRS (NAD83 / North Carolina State Plane)
target_crs = CRS("EPSG:2264")

# Create a transformer object
transformer = Transformer.from_crs(source_crs, target_crs, always_xy=True)

# Apply the transformation to the 'latitude' and 'longitude' columns
df_filtered['x_coord'], df_filtered['y_coord'] = transformer.transform(
    df_filtered['longitude'].values,
    df_filtered['latitude'].values
)

print("Coordinates transformed successfully!")

"""### K-Means Clustering by X,Y coordinate

"""

from sklearn.cluster import KMeans
import geopandas as gpd

# Prepare data for clustering
X_cluster = df_filtered[['x_coord', 'y_coord']]

# Initialize and fit KMeans model
k = 20
kmeans = KMeans(n_clusters=k, random_state=12, n_init=10)
df_filtered['geoCluster'] = kmeans.fit_predict(X_cluster)

# Load the Wake County shapefile
wake_county_map = gpd.read_file('/content/borders.shp')

# The current CRS of the shapefile is likely WGS84 (EPSG:4326), check if it's not and adjust
# Let's assume it's EPSG:4326 and transform it to EPSG:2264 (NAD83 / North Carolina State Plane)
# which matches the coordinate system of x_coord and y_coord
if wake_county_map.crs != 'EPSG:2264':
    wake_county_map = wake_county_map.to_crs(epsg=2264)

# Create a GeoDataFrame from the clustered points for easy plotting with geopandas
# The x_coord and y_coord are already in EPSG:2264
geodata = gpd.GeoDataFrame(
    df_filtered,
    geometry=gpd.points_from_xy(df_filtered['x_coord'], df_filtered['y_coord']),
    crs="EPSG:2264"
)

# Plotting the map and clusters
fig, ax = plt.subplots(1, 1, figsize=(12, 10))

# Plot the Wake County map
wake_county_map.plot(ax=ax, color='lightgray', edgecolor='black', alpha=0.7)

# Create a mappable object for the colorbar
vmin, vmax = df_filtered['geoCluster'].min(), df_filtered['geoCluster'].max()
norm = Normalize(vmin=vmin, vmax=vmax)
cmap = plt.get_cmap('viridis')
sm = ScalarMappable(norm=norm, cmap=cmap)
sm.set_array(df_filtered['geoCluster'])

# Overlay the K-Means clusters (without legend, we'll add it manually)
geodata.plot(column='geoCluster', cmap='viridis', markersize=10, ax=ax, alpha=0.8)

# Add colorbar manually
cbar = fig.colorbar(sm, ax=ax, shrink=0.7)
cbar.set_label('Geographical Cluster')

# Set ticks to be integers from 0 to k-1
cbar.set_ticks(np.arange(k))
cbar.set_ticklabels(np.arange(k).astype(str)) # Convert to string for labels

ax.set_title('K-Means Clusters on Wake County Map')
ax.set_xlabel('X Coordinate (ft)')
ax.set_ylabel('Y Coordinate (ft)')
ax.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### XGBoost Model Training"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define features (X) and target (y)
features = ['city', 'interior_sqft', 'baths', 'beds', 'x_coord', 'y_coord', 'geoCluster', 'walkIdx']
target = 'log_price'

X = df_filtered[features]
y = df_filtered[target]

# Identify categorical and numerical features
categorical_features = ['city', 'geoCluster']
numerical_features = ['interior_sqft', 'baths', 'beds', 'x_coord', 'y_coord', 'walkIdx']

# Create a column transformer for one-hot encoding categorical features
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', 'passthrough', numerical_features)
    ])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")
print("Data prepared and split successfully!")

display(X_train.head())
display(y_train.head())

import xgboost as xgb

# Create the XGBoost Regressor model pipeline with chosen hyperparameters
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', xgb.XGBRegressor(objective='reg:squarederror', random_state=42,
                                   n_estimators=1000, learning_rate=0.05, max_depth=4))
])

# Train the model
model.fit(X_train, y_train)

print("XGBoost model trained successfully with predefined hyperparameters!")

"""### Hyperparameter Tuning"""

# Hyperparameter tuning is skipped as per user request.
# The model 'best_model' will be set to the 'model' trained in the previous cell.
best_model = model

print("Hyperparameter tuning skipped. 'best_model' is set to the initially trained model.")

# Re-execute cell 32a6b931 to ensure ROI and investment_value are correctly calculated and displayed
# Define features (X) - Re-added for robustness against NameError
features = ['city', 'interior_sqft', 'baths', 'beds', 'x_coord', 'y_coord', 'geoCluster', 'walkIdx']

# Predict log_price for the entire filtered dataset using the best model
X_all = df_filtered[features]
y_pred_log_all = best_model.predict(X_all)

# Inverse transform the predictions back to the original price scale
predicted_price = np.expm1(y_pred_log_all)

# Add predicted_price as a column to df_filtered
df_filtered['predicted_price'] = predicted_price

# Calculate residuals (Actual Price - Predicted Price)
df_filtered['residuals'] = df_filtered['price'] - df_filtered['predicted_price']

# Drop the 'Unnamed: 0' column if it exists and is not needed
if 'Unnamed: 0' in df_filtered.columns:
    df_filtered = df_filtered.drop(columns=['Unnamed: 0'])

# Define n for top/bottom residuals
n_display = 10

# Determine 'underpriced', 'overpriced', 'middle' categories for the entire dataset
df_filtered['value_priced'] = 'middle'

# Identify indices for 'underpriced' and 'overpriced' based on user's definition:
# 'underpriced': Actual Price is significantly LESS than Predicted Price (negative residual)
underpriced_indices_all = df_filtered['residuals'].sort_values().head(n_display).index

# 'overpriced': Actual Price is significantly MORE than Predicted Price (positive residual)
overpriced_indices_all = df_filtered['residuals'].sort_values(ascending=False).head(n_display).index

# Assign labels based on the corrected intuitive meaning:
df_filtered.loc[underpriced_indices_all, 'value_priced'] = 'underpriced'
df_filtered.loc[overpriced_indices_all, 'value_priced'] = 'overpriced'

# Re-execute the cell that caused the error after 'predicted_price' is available
# Calculate ROI: (Predicted Value - Actual Value) / Actual Value
df_filtered['ROI'] = (df_filtered['predicted_price'] - df_filtered['price']) / df_filtered['price']

# Initialize investment_value column
df_filtered['investment_value'] = 'middle'

# Identify indices for 'high' and 'low' investment value
# 'high' investment value: high ROI (predicted price >> actual price)
high_investment_indices = df_filtered['ROI'].sort_values(ascending=False).head(n_display).index

# 'low' investment value: low ROI (predicted price << actual price)
low_investment_indices = df_filtered['ROI'].sort_values(ascending=True).head(n_display).index

# Assign labels
df_filtered.loc[high_investment_indices, 'investment_value'] = 'high'
df_filtered.loc[low_investment_indices, 'investment_value'] = 'low'

print("ROI and investment_value calculated successfully!")

print(f"Top {n_display} 'High Investment Value' Properties (Highest ROI):")
# Create a temporary DataFrame for display with formatted ROI
display_df_high = df_filtered.loc[high_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].copy()
display_df_high['ROI'] = display_df_high['ROI'].apply(lambda x: f'{x:.2%}')
display(display_df_high.sort_values(by='ROI', ascending=False))

print(f"Top {n_display} 'Low Investment Value' Properties (Lowest ROI):")
# Create a temporary DataFrame for display with formatted ROI
display_df_low = df_filtered.loc[low_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].copy()
display_df_low['ROI'] = display_df_low['ROI'].apply(lambda x: f'{x:.2%}')
display(display_df_low.sort_values(by='ROI', ascending=True))

# Re-execute cell d2ff2dff for updated visualizations
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Plot layout
fig, axes = plt.subplots(2, 1, figsize=(10, 16)) # Increased height for stacked plots


# Set data frame labels for plotting for residuals
plot_df_residuals = pd.DataFrame({
    'Actual Price': df_filtered['price'],
    'Predicted Price': df_filtered['predicted_price'],
    'Category': df_filtered['value_priced']
})

# --- Plot 1: Actual vs. Predicted Plot Color-Coded by Value Diffence ---

# Define a for residual categories
color_map_residuals = {'underpriced': 'limegreen', 'overpriced': 'red', 'middle': 'lightsteelblue'}

# Plot middle points first with lower order
# to avoid covering up important points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'middle'],
    color=color_map_residuals['middle'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=3,
    label='middle'
)

# Plot 'underpriced' points (actual < predicted, above line)
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'underpriced'],
    color=color_map_residuals['underpriced'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=5,
    label='underpriced'
)

# Plot 'overpriced' points (actual > predicted, below line)
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'overpriced'],
    color=color_map_residuals['overpriced'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=5,
    label='overpriced'
)

axes[0].set_title('Actual vs. Predicted Prices by Value Difference')
axes[0].set_xlabel('Actual Price ($)')
axes[0].set_ylabel('Predicted Price ($)')

# Add a line for perfect prediction
max_val = max(plot_df_residuals['Actual Price'].max(), plot_df_residuals['Predicted Price'].max())
min_val = min(plot_df_residuals['Actual Price'].min(), plot_df_residuals['Predicted Price'].min())
axes[0].plot([min_val, max_val], [min_val, max_val], color='orange', linestyle='--', lw=2, label='Perfect Prediction', zorder=4)
axes[0].grid(True)
axes[0].legend(title='Value Difference')


# --- Plot 2: Actual vs. Predicted Plot Color-Coded by ROI ---

# Define a consistent color mapping with adjusted colors
color_map_investment = {'high': 'limegreen', 'low': 'red', 'middle': 'lightsteelblue'}

# Set data frame labels for plotting for investment value
plot_df_investment = pd.DataFrame({
    'Actual Price': df_filtered['price'],
    'Predicted Price': df_filtered['predicted_price'],
    'Category': df_filtered['investment_value']
})

# Plot middle points first with lower order
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'middle'],
    color=color_map_investment['middle'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=3,
    label='middle'
)

# Plot 'high' investment points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'high'],
    color=color_map_investment['high'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=5,
    label='high'
)

# Plot 'low' investment points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'low'],
    color=color_map_investment['low'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=5,
    label='low'
)

axes[1].set_title('Actual vs. Predicted Prices by Return on Investment')
axes[1].set_xlabel('Actual Price ($)')
axes[1].set_ylabel('Predicted Price ($)')

# Add a line for perfect prediction
axes[1].plot([min_val, max_val], [min_val, max_val], color='orange', linestyle='--', lw=2, label='Perfect Prediction', zorder=4)
axes[1].grid(True)
axes[1].legend(title='Investment Value')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# Re-execute cell 18677f41 for updated feature importance analysis
# Initialize a dictionary to store aggregated importances
aggregated_importances = {}

# Get feature names after one-hot encoding
onehot_features = best_model.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_features)
all_features_names = np.concatenate([onehot_features, numerical_features])

# Get the trained XGBoost regressor from the best_model pipeline
xgb_regressor_instance = best_model.named_steps['regressor']

# Map importances to their feature names
feature_importance_map = dict(zip(all_features_names, xgb_regressor_instance.feature_importances_))

# Aggregate importances for categorical features
for feature_name in all_features_names:
    if feature_name.startswith('city_'):
        category_name = 'city'
    elif feature_name.startswith('geoCluster_'):
        category_name = 'geoCluster'
    else:
        category_name = feature_name # It's a numerical feature

    aggregated_importances[category_name] = aggregated_importances.get(category_name, 0) + feature_importance_map[feature_name]

# Create a DataFrame for aggregated importances
aggregated_importance_df = pd.DataFrame({
    'Feature': list(aggregated_importances.keys()),
    'Importance': list(aggregated_importances.values())
})

# Sort by importance
aggregated_importance_df = aggregated_importance_df.sort_values(by='Importance', ascending=False)

display(aggregated_importance_df)

# Visualize aggregated feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', data=aggregated_importance_df.head(15), palette='viridis', hue='Feature', legend=False)
plt.title('Feature Importances (XGBoost)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Re-execute cell e5ae42a1 for updated visualizations based on new ROI
import geopandas as gpd
from shapely.geometry import Point

fig, axes = plt.subplots(2, 2, figsize=(18, 12)) # Changed to 2x2 grid
axes = axes.flatten() # Flatten the 2x2 array of axes for easier indexing
fig.suptitle('Relationship with Price for Key Features', fontsize=18)

# --- Plot 1 (0): Average Price Per Geographical Cluster on Wake County Map ---

# Calculate the average price per cluster (re-define as it was in a separate cell previously)
avg_price_per_cluster = df_filtered.groupby('geoCluster')['price'].mean().reset_index()

# Get cluster centroids from the KMeans model
cluster_centroids = pd.DataFrame(kmeans.cluster_centers_, columns=['x_coord_centroid', 'y_coord_centroid'])
cluster_centroids['geoCluster'] = cluster_centroids.index

# Merge average prices with centroids
cluster_data_for_map = pd.merge(avg_price_per_cluster, cluster_centroids, on='geoCluster')

# Create a GeoDataFrame for centroids
centroids_geodata = gpd.GeoDataFrame(
    cluster_data_for_map,
    geometry=gpd.points_from_xy(cluster_data_for_map['x_coord_centroid'], cluster_data_for_map['y_coord_centroid']),
    crs="EPSG:2264"
)

# Plot the Wake County map
wake_county_map.plot(ax=axes[0], color='lightgray', edgecolor='black', alpha=0.7)

# Plot the individual properties, colored by cluster, with full opacity and added zorder
geodata.plot(column='geoCluster', cmap='viridis', markersize=35, ax=axes[0], alpha=1.0, legend=True, zorder=1)

# Overlay the cluster centroids with average price as text
for idx, row in centroids_geodata.iterrows():
    axes[0].annotate(text=f'${row["price"]:,.0f}', xy=(row.geometry.x, row.geometry.y),
                xytext=(5, 5), textcoords="offset points",
                ha='center', va='center', fontsize=11, color='black',
                bbox=dict(boxstyle="round,pad=0", fc='white', ec='white', alpha=1.0, lw=1.0), zorder=2)

axes[0].set_title('Average Price Per Geographical Cluster')
axes[0].set_xlabel('X Coordinate (ft)')
axes[0].set_ylabel('Y Coordinate (ft)')
axes[0].grid(True, linestyle='--', alpha=0.6)

# --- Plot 2 (1): Square Footage vs. Price ---
sns.scatterplot(x='interior_sqft', y='price', data=df_filtered, alpha=0.6, ax=axes[1], color=sns.color_palette('viridis')[2])
axes[1].set_title('Price vs. Interior Square Footage')
axes[1].set_xlabel('Area (sq ft)')
axes[1].set_ylabel('Price')

# --- Plot 3 (2): City vs. Price ---
sns.barplot(x='city', y='price', data=df_filtered.groupby('city')['price'].mean().reset_index().sort_values(by='price', ascending=False), palette='viridis', hue='city', legend=False, ax=axes[2])
axes[2].set_title('Price Distribution by City')
axes[2].set_xlabel('City')
axes[2].set_ylabel('Price')
axes[2].tick_params(axis='x', rotation=90)

# --- Plot 4 (3): Baths vs. Price ---
sns.barplot(x='baths', y='price', data=df_filtered.groupby('baths')['price'].mean().reset_index(), palette='viridis', hue='baths', legend=False, ax=axes[3])
axes[3].set_title('Price Distribution by Number of Baths')
axes[3].set_xlabel('Number of Baths')
axes[3].set_ylabel('Average Price')

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap
plt.show()

# Evaluate the model on the test set
from sklearn.metrics import mean_squared_error, r2_score

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error on Test Set: {mse:.4f}")
print(f"R-squared on Test Set: {r2:.4f}")

# Graph actual vs. predicted values
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.xlabel("Actual Log Price")
plt.ylabel("Predicted Log Price")
plt.title("Actual vs. Predicted Log Prices (XGBoost)")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # Line for perfect prediction
plt.grid(True)
plt.show()

"""### Evaluating Model Performance on Original Price Scale (undoing the log transform)"""

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Inverse transform y_test and y_pred back to original price scale
y_test_original = np.expm1(y_test)
y_pred_original = np.expm1(y_pred)

# Calculate metrics on the original price scale
mse_original = mean_squared_error(y_test_original, y_pred_original)
rmse_original = np.sqrt(mse_original)
mae_original = mean_absolute_error(y_test_original, y_pred_original)
r2_original = r2_score(y_test_original, y_pred_original)

print(f"--- Metrics on Original Price Scale ---")
print(f"Mean Squared Error (Original): {mse_original:.2f}")
print(f"Root Mean Squared Error (Original): {rmse_original:.2f}")
print(f"Mean Absolute Error (Original): {mae_original:.2f}")
print(f"R-squared (Original): {r2_original:.4f}")

# Visualize actual vs. predicted values on original scale
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test_original, y=y_pred_original, alpha=0.6)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs. Predicted Prices (XGBoost)")
plt.plot([y_test_original.min(), y_test_original.max()], [y_test_original.min(), y_test_original.max()], 'r--', lw=2) # Line for perfect prediction
plt.grid(True)
plt.show()

"""Use Residuals to Find Under and Over Priced Houses"""

# Define features (X) - Re-added for robustness against NameError
features = ['city', 'interior_sqft', 'baths', 'beds', 'x_coord', 'y_coord', 'geoCluster', 'walkIdx']

# Predict log_price for the entire filtered dataset using the best model
X_all = df_filtered[features]
y_pred_log_all = best_model.predict(X_all)

# Inverse transform the predictions back to the original price scale
predicted_price = np.expm1(y_pred_log_all)

# Add predicted_price as a column to df_filtered
df_filtered['predicted_price'] = predicted_price

# Calculate residuals (Actual Price - Predicted Price)
df_filtered['residuals'] = df_filtered['price'] - df_filtered['predicted_price']

# Drop the 'Unnamed: 0' column if it exists and is not needed
if 'Unnamed: 0' in df_filtered.columns:
    df_filtered = df_filtered.drop(columns=['Unnamed: 0'])

# Define n for top/bottom residuals
n_display = 10

# Determine 'underpriced', 'overpriced', 'middle' categories for the entire dataset
df_filtered['value_priced'] = 'middle'

# Identify indices for 'underpriced' and 'overpriced' based on user's definition:
# 'underpriced': Actual Price is significantly LESS than Predicted Price (negative residual)
underpriced_indices_all = df_filtered['residuals'].sort_values().head(n_display).index

# 'overpriced': Actual Price is significantly MORE than Predicted Price (positive residual)
overpriced_indices_all = df_filtered['residuals'].sort_values(ascending=False).head(n_display).index

# Assign labels based on the corrected intuitive meaning:
df_filtered.loc[underpriced_indices_all, 'value_priced'] = 'underpriced'
df_filtered.loc[overpriced_indices_all, 'value_priced'] = 'overpriced'

# Re-execute the cell that caused the error after 'predicted_price' is available
# Calculate ROI: (Predicted Value - Actual Value) / Actual Value
df_filtered['ROI'] = (df_filtered['predicted_price'] - df_filtered['price']) / df_filtered['price']

# Initialize investment_value column
df_filtered['investment_value'] = 'middle'

# Identify indices for 'high' and 'low' investment value
# 'high' investment value: high ROI (predicted price >> actual price)
high_investment_indices = df_filtered['ROI'].sort_values(ascending=False).head(n_display).index

# 'low' investment value: low ROI (predicted price << actual price)
low_investment_indices = df_filtered['ROI'].sort_values(ascending=True).head(n_display).index

# Assign labels
df_filtered.loc[high_investment_indices, 'investment_value'] = 'high'
df_filtered.loc[low_investment_indices, 'investment_value'] = 'low'

print("ROI and investment_value calculated successfully!")

print(f"Top {n_display} 'High Investment Value' Properties (Highest ROI):")
# Create a temporary DataFrame for display with formatted ROI
display_df_high = df_filtered.loc[high_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].copy()
display_df_high['ROI'] = display_df_high['ROI'].apply(lambda x: f'{x:.2%}')
display(display_df_high.sort_values(by='ROI', ascending=False))

print(f"Top {n_display} 'Low Investment Value' Properties (Lowest ROI):")
# Create a temporary DataFrame for display with formatted ROI
display_df_low = df_filtered.loc[low_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].copy()
display_df_low['ROI'] = display_df_low['ROI'].apply(lambda x: f'{x:.2%}')
display(display_df_low.sort_values(by='ROI', ascending=True))

"""N Most Underprided Houses"""

display_columns = ['residuals', 'address', 'city', 'price', 'predicted_price', 'interior_sqft', 'baths', 'beds', 'walkIdx', 'geoCluster']

print(f"Top {n_display} 'Underpriced' Properties:")
display(df_filtered.loc[underpriced_indices_all, display_columns].sort_values(by='residuals', ascending=True))

"""N Most Overpriced Houses"""

print(f"Top {n_display} 'Overpriced' Properties:")
display(df_filtered.loc[overpriced_indices_all, display_columns].sort_values(by='residuals', ascending=False))

"""### Calculate ROI and Investment Value Categories"""

# Calculate ROI: (Predicted Value - Actual Value) / Actual Value
df_filtered['ROI'] = (df_filtered['predicted_price'] - df_filtered['price']) / df_filtered['price']

# Initialize investment_value column
df_filtered['investment_value'] = 'middle'

# Identify indices for 'high' and 'low' investment value
# 'high' investment value: high ROI (predicted price >> actual price)
high_investment_indices = df_filtered['ROI'].sort_values(ascending=False).head(n_display).index

# 'low' investment value: low ROI (predicted price << actual price)
low_investment_indices = df_filtered['ROI'].sort_values(ascending=True).head(n_display).index

# Assign labels
df_filtered.loc[high_investment_indices, 'investment_value'] = 'high'
df_filtered.loc[low_investment_indices, 'investment_value'] = 'low'

print("ROI and investment_value calculated successfully!")

print(f"Top {n_display} 'High Investment Value' Properties (Highest ROI):")
display(df_filtered.loc[high_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].sort_values(by='ROI', ascending=False))

print(f"Top {n_display} 'Low Investment Value' Properties (Lowest ROI):")
display(df_filtered.loc[low_investment_indices, ['ROI', 'address', 'city', 'price', 'predicted_price']].sort_values(by='ROI', ascending=True))

"""### Visualizing Value Differnce and ROI"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Plot layout
fig, axes = plt.subplots(2, 1, figsize=(10, 16)) # Increased height for stacked plots


# Set data frame labels for plotting for residuals
plot_df_residuals = pd.DataFrame({
    'Actual Price': df_filtered['price'],
    'Predicted Price': df_filtered['predicted_price'],
    'Category': df_filtered['value_priced']
})

# --- Plot 1: Actual vs. Predicted Plot Color-Coded by Value Diffence ---

# Define a for residual categories
color_map_residuals = {'underpriced': 'limegreen', 'overpriced': 'red', 'middle': 'lightsteelblue'}

# Plot middle points first with lower order
# to avoid covering up important points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'middle'],
    color=color_map_residuals['middle'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=3,
    label='middle'
)

# Plot 'underpriced' points (actual < predicted, above line)
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'underpriced'],
    color=color_map_residuals['underpriced'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=5,
    label='underpriced'
)

# Plot 'overpriced' points (actual > predicted, below line)
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_residuals[plot_df_residuals['Category'] == 'overpriced'],
    color=color_map_residuals['overpriced'],
    alpha=0.7,
    ax=axes[0],
    s=50,
    zorder=5,
    label='overpriced'
)

axes[0].set_title('Actual vs. Predicted Prices by Value Difference')
axes[0].set_xlabel('Actual Price ($)')
axes[0].set_ylabel('Predicted Price ($)')

# Add a line for perfect prediction
max_val = max(plot_df_residuals['Actual Price'].max(), plot_df_residuals['Predicted Price'].max())
min_val = min(plot_df_residuals['Actual Price'].min(), plot_df_residuals['Predicted Price'].min())
axes[0].plot([min_val, max_val], [min_val, max_val], color='orange', linestyle='--', lw=2, label='Perfect Prediction', zorder=4)
axes[0].grid(True)
axes[0].legend(title='Value Difference')


# --- Plot 2: Actual vs. Predicted Plot Color-Coded by ROI ---

# Define a consistent color mapping with adjusted colors
color_map_investment = {'high': 'limegreen', 'low': 'red', 'middle': 'lightsteelblue'}

# Set data frame labels for plotting for investment value
plot_df_investment = pd.DataFrame({
    'Actual Price': df_filtered['price'],
    'Predicted Price': df_filtered['predicted_price'],
    'Category': df_filtered['investment_value']
})

# Plot middle points first with lower order
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'middle'],
    color=color_map_investment['middle'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=3,
    label='middle'
)

# Plot 'high' investment points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'high'],
    color=color_map_investment['high'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=5,
    label='high'
)

# Plot 'low' investment points
sns.scatterplot(
    x='Actual Price',
    y='Predicted Price',
    data=plot_df_investment[plot_df_investment['Category'] == 'low'],
    color=color_map_investment['low'],
    alpha=0.7,
    ax=axes[1],
    s=50,
    zorder=5,
    label='low'
)

axes[1].set_title('Actual vs. Predicted Prices by Return on Investment')
axes[1].set_xlabel('Actual Price ($)')
axes[1].set_ylabel('Predicted Price ($)')

# Add a line for perfect prediction
axes[1].plot([min_val, max_val], [min_val, max_val], color='orange', linestyle='--', lw=2, label='Perfect Prediction', zorder=4)
axes[1].grid(True)
axes[1].legend(title='Investment Value')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""

### Feature Importance Analysis
"""

# Initialize a dictionary to store aggregated importances
aggregated_importances = {}

# Get feature names after one-hot encoding
onehot_features = best_model.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_features)
all_features_names = np.concatenate([onehot_features, numerical_features])

# Get the trained XGBoost regressor from the best_model pipeline
xgb_regressor_instance = best_model.named_steps['regressor']

# Map importances to their feature names
feature_importance_map = dict(zip(all_features_names, xgb_regressor_instance.feature_importances_))

# Aggregate importances for categorical features
for feature_name in all_features_names:
    if feature_name.startswith('city_'):
        category_name = 'city'
    elif feature_name.startswith('geoCluster_'):
        category_name = 'geoCluster'
    else:
        category_name = feature_name # It's a numerical feature

    aggregated_importances[category_name] = aggregated_importances.get(category_name, 0) + feature_importance_map[feature_name]

# Create a DataFrame for aggregated importances
aggregated_importance_df = pd.DataFrame({
    'Feature': list(aggregated_importances.keys()),
    'Importance': list(aggregated_importances.values())
})

# Sort by importance
aggregated_importance_df = aggregated_importance_df.sort_values(by='Importance', ascending=False)

display(aggregated_importance_df)

# Visualize aggregated feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x='Importance', y='Feature', data=aggregated_importance_df.head(15), palette='viridis', hue='Feature', legend=False)
plt.title('Feature Importances (XGBoost)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import geopandas as gpd
from shapely.geometry import Point

fig, axes = plt.subplots(2, 2, figsize=(18, 12)) # Changed to 2x2 grid
axes = axes.flatten() # Flatten the 2x2 array of axes for easier indexing
fig.suptitle('Relationship with Price for Key Features', fontsize=18)

# --- Plot 1 (0): Average Price Per Geographical Cluster on Wake County Map ---

# Calculate the average price per cluster (re-define as it was in a separate cell previously)
avg_price_per_cluster = df_filtered.groupby('geoCluster')['price'].mean().reset_index()

# Get cluster centroids from the KMeans model
cluster_centroids = pd.DataFrame(kmeans.cluster_centers_, columns=['x_coord_centroid', 'y_coord_centroid'])
cluster_centroids['geoCluster'] = cluster_centroids.index

# Merge average prices with centroids
cluster_data_for_map = pd.merge(avg_price_per_cluster, cluster_centroids, on='geoCluster')

# Create a GeoDataFrame for centroids
centroids_geodata = gpd.GeoDataFrame(
    cluster_data_for_map,
    geometry=gpd.points_from_xy(cluster_data_for_map['x_coord_centroid'], cluster_data_for_map['y_coord_centroid']),
    crs="EPSG:2264"
)

# Plot the Wake County map
wake_county_map.plot(ax=axes[0], color='lightgray', edgecolor='black', alpha=0.7)

# Plot the individual properties, colored by cluster, with full opacity and added zorder
geodata.plot(column='geoCluster', cmap='viridis', markersize=35, ax=axes[0], alpha=1.0, legend=True, zorder=1)

# Overlay the cluster centroids with average price as text
for idx, row in centroids_geodata.iterrows():
    axes[0].annotate(text=f'${row["price"]:,.0f}', xy=(row.geometry.x, row.geometry.y),
                xytext=(5, 5), textcoords="offset points",
                ha='center', va='center', fontsize=11, color='black',
                bbox=dict(boxstyle="round,pad=0", fc='white', ec='white', alpha=1.0, lw=1.0), zorder=2)

axes[0].set_title('Average Price Per Geographical Cluster')
axes[0].set_xlabel('X Coordinate (ft)')
axes[0].set_ylabel('Y Coordinate (ft)')
axes[0].grid(True, linestyle='--', alpha=0.6)

# --- Plot 2 (1): Square Footage vs. Price ---
sns.scatterplot(x='interior_sqft', y='price', data=df_filtered, alpha=0.6, ax=axes[1], color=sns.color_palette('viridis')[2])
axes[1].set_title('Price vs. Interior Square Footage')
axes[1].set_xlabel('Area (sq ft)')
axes[1].set_ylabel('Price')

# --- Plot 3 (2): City vs. Price ---
sns.barplot(x='city', y='price', data=df_filtered.groupby('city')['price'].mean().reset_index().sort_values(by='price', ascending=False), palette='viridis', hue='city', legend=False, ax=axes[2])
axes[2].set_title('Price Distribution by City')
axes[2].set_xlabel('City')
axes[2].set_ylabel('Price')
axes[2].tick_params(axis='x', rotation=90)

# --- Plot 4 (3): Baths vs. Price ---
sns.barplot(x='baths', y='price', data=df_filtered.groupby('baths')['price'].mean().reset_index(), palette='viridis', hue='baths', legend=False, ax=axes[3])
axes[3].set_title('Price Distribution by Number of Baths')
axes[3].set_xlabel('Number of Baths')
axes[3].set_ylabel('Average Price')

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap
plt.show()